const BookingActionTypes = {
    CHANGE_DATE_BOOKING: "CHANGE_DATE_BOOKING",
    CHANGE_SLOT: "CHANGE_SLOT",
    CHANGE_BOOKING: "CHANGE_BOOKING",
    CHANGE_SLOT_RELOAD: "CHANGE_SLOT_RELOAD",
    ADD_NEW_PERFUME: "ADD_NEW_PERFUME",
    REMOVE_PERFUME: "REMOVE_PERFUME",
    TOGGLE_MODAL_CREATE: "TOGGLE_MODAL_CREATE",
    TOGGLE_MODAL_VIEW: "TOGGLE_MODAL_VIEW",
    TOGGLE_SUBMIT: "TOGGLE_SUBMIT",
    CLEAR_BOOKING: "CLEAR_BOOKING",
}

export default BookingActionTypes;